// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Input = require("../Util/input.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var input = Input.Input.getInput(/* Single */0, 3);

var twoDimensionArray = Belt_Array.map(input, (function (a) {
        return a.split("");
      }));

function findTree(param) {
  var y = param[1];
  var x = param[0];
  return Belt_Array.keep(Belt_Array.mapWithIndex(Belt_Array.keepWithIndex(twoDimensionArray, (function (param, index) {
                        return Caml_int32.mod_(index, y) === 0;
                      })), (function (index, arr) {
                    var length = arr.length;
                    var targetX = Caml_int32.mod_(Math.imul(index, x), length);
                    return Belt_Option.getWithDefault(Belt_Array.get(arr, targetX), "");
                  })), (function (str) {
                return str === "#";
              })).length;
}

console.log(findTree([
          3,
          1
        ]));

var directions = [
  [
    1,
    1
  ],
  [
    3,
    1
  ],
  [
    5,
    1
  ],
  [
    7,
    1
  ],
  [
    1,
    2
  ]
];

console.log(Belt_Array.reduce(Belt_Array.map(directions, findTree), 1, (function (acc, cur) {
            return Math.imul(acc, cur);
          })));

exports.input = input;
exports.twoDimensionArray = twoDimensionArray;
exports.findTree = findTree;
exports.directions = directions;
/* input Not a pure module */
