// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_SetInt = require("rescript/lib/js/belt_SetInt.js");

var input = Fs.readFileSync("input/Week1/Year2020Day9.sample.txt", "utf8");

function id(t) {
  return t;
}

var arr = Belt_Array.keepMap(input.split("\n"), Belt_Int.fromString);

function makeCombination(arr) {
  return Belt_SetInt.fromArray(Belt_Array.reduceWithIndex(arr, [], (function (acc, v, i) {
                    return Belt_Array.concat(acc, Belt_Array.map(Belt_Array.slice(arr, i + 1 | 0, 25), (function (w) {
                                      return v + w | 0;
                                    })));
                  })));
}

function make(arr, value) {
  var match = arr.length;
  if (match !== 5) {
    return ;
  }
  if (value === undefined) {
    return ;
  }
  var set = makeCombination(arr);
  if (Belt_SetInt.has(set, value)) {
    return ;
  } else {
    return value;
  }
}

console.log(Belt_Array.keepMap(Belt_Array.mapWithIndex(arr, (function (idx, param) {
                return make(Belt_Array.slice(arr, idx, 25), Belt_Array.get(arr, idx + 5 | 0));
              })), id));

exports.input = input;
exports.id = id;
exports.arr = arr;
exports.makeCombination = makeCombination;
exports.make = make;
/* input Not a pure module */
