// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function get(t, fileNum) {
  if (t) {
    return Fs.readFileSync("input/Year2020Day" + String(fileNum) + ".sample.txt", "utf8").split("\n\n");
  } else {
    return Fs.readFileSync("input/Year2020Day" + String(fileNum) + ".sample.txt", "utf8").split("\n");
  }
}

var Input = {
  get: get
};

exports.Input = Input;
/* fs Not a pure module */
