// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");

var input = Fs.readFileSync("input/Week1/Year2020Day7.sample.txt", "utf8");

var list = Belt_List.fromArray(input.split("\n"));

Belt_List.forEach(list, (function (str) {
        var match = str.split("contain");
        if (match.length !== 2) {
          throw {
                RE_EXN_ID: "Match_failure",
                _1: [
                  "Year2020Day7.res",
                  10,
                  8
                ],
                Error: new Error()
              };
        }
        var splitted = match[1];
        console.log(Belt_List.fromArray(splitted.split(", ")));
        
      }));

exports.input = input;
exports.list = list;
/* input Not a pure module */
