// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var input = Fs.readFileSync("input/Week1/Year2020Day2.sample.txt", "utf8");

var li = Belt_List.fromArray(input.split("\n"));

function id(a) {
  return a;
}

function split(string) {
  return Belt_Array.keepMap(string.split(/-|\s|:\s/g), id);
}

function intStringToInt(s) {
  return Belt_Option.getExn(Belt_Int.fromString(s));
}

function parsing(fullString) {
  var splitted = split(fullString);
  if (splitted.length !== 4) {
    return ;
  }
  var a = splitted[0];
  var b = splitted[1];
  var c = splitted[2];
  var d = splitted[3];
  return {
          low: Belt_Option.getExn(Belt_Int.fromString(a)),
          high: Belt_Option.getExn(Belt_Int.fromString(b)),
          target: c,
          source: d
        };
}

function judgeX(p) {
  var target = p.target;
  var cnt = Belt_Array.keep(p.source.split(""), (function (x) {
          return x === target;
        })).length;
  if (cnt >= p.low) {
    return cnt <= p.high;
  } else {
    return false;
  }
}

function judgeY(p) {
  var target = p.target;
  var sourceToArr = p.source.split("");
  var lowCharIsTarget = Belt_Array.getExn(sourceToArr, p.low - 1 | 0) === target;
  var highCharIsTarget = Belt_Array.getExn(sourceToArr, p.high - 1 | 0) === target;
  return lowCharIsTarget !== highCharIsTarget;
}

console.log(Belt_List.size(Belt_List.keep(Belt_List.keepMap(li, parsing), judgeX)));

console.log(Belt_List.size(Belt_List.keep(Belt_List.keepMap(li, parsing), judgeY)));

exports.input = input;
exports.li = li;
exports.id = id;
exports.split = split;
exports.intStringToInt = intStringToInt;
exports.parsing = parsing;
exports.judgeX = judgeX;
exports.judgeY = judgeY;
/* input Not a pure module */
