// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

var input = Fs.readFileSync("input/Week1/Year2020Day7.sample.txt", "utf8");

var list = input.split("\n");

function id(t) {
  return t;
}

var re = /(.*?)contain(.*?)(?:$)/gm;

console.log(Belt_Array.map(list, (function (s) {
            return Caml_option.null_to_opt(s.match(re));
          })));

exports.input = input;
exports.list = list;
exports.id = id;
exports.re = re;
/* input Not a pure module */
