// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_SetInt = require("rescript/lib/js/belt_SetInt.js");

var input = Fs.readFileSync("input/Week1/Year2020Day8.sample.txt", "utf8");

var arr = input.split("\n");

var length = arr.length;

var val = {
  contents: 0
};

var currentIdx = {
  contents: 0
};

var set = {
  contents: undefined
};

function jump(i) {
  currentIdx.contents = currentIdx.contents + i | 0;
  
}

function acc(i) {
  currentIdx.contents = currentIdx.contents + 1 | 0;
  val.contents = val.contents + i | 0;
  
}

function $$do(s) {
  var splited = s.split(" ", 2);
  if (splited.length !== 2) {
    return ;
  }
  var match = splited[0];
  switch (match) {
    case "acc" :
        var v = splited[1];
        return acc(Belt_Option.getExn(Belt_Int.fromString(v)));
    case "jmp" :
        var v$1 = splited[1];
        return jump(Belt_Option.getExn(Belt_Int.fromString(v$1)));
    case "nop" :
        currentIdx.contents = currentIdx.contents + 1 | 0;
        return ;
    default:
      return ;
  }
}

while(currentIdx.contents < length && !Belt_SetInt.has(set.contents, currentIdx.contents)) {
  set.contents = Belt_SetInt.add(set.contents, currentIdx.contents);
  $$do(Belt_Array.getExn(arr, currentIdx.contents));
};

console.log(val.contents);

exports.input = input;
exports.arr = arr;
exports.length = length;
exports.val = val;
exports.currentIdx = currentIdx;
exports.set = set;
exports.jump = jump;
exports.acc = acc;
exports.$$do = $$do;
/* input Not a pure module */
