// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var input = Fs.readFileSync("input/Week1/Year2020Day3.sample.txt", "utf8");

function fn(a, b) {
  return a + b | 0;
}

function fn2(param) {
  return 3 + param | 0;
}

console.log(input);

var arr = Belt_List.fromArray(input.split("\n"));

var rowLength = Belt_Option.mapWithDefault(Belt_List.head(arr), 0, (function (prim) {
        return prim.length;
      }));

var a = Belt_List.length(Belt_List.keep(Belt_List.mapWithIndex(Belt_List.map(Belt_List.keep(arr, (function (a) {
                        return a !== "";
                      })), (function (str) {
                    return str.split("");
                  })), (function (idx, arr) {
                return Caml_array.get(arr, Math.imul(idx, 3) - Math.imul(Caml_int32.div(Math.imul(idx, 3), rowLength), rowLength) | 0);
              })), (function (x) {
            return x === "#";
          })));

console.log(a);

exports.input = input;
exports.fn = fn;
exports.fn2 = fn2;
exports.arr = arr;
exports.rowLength = rowLength;
exports.a = a;
/* input Not a pure module */
