// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

var input = Fs.readFileSync("input/Week1/Year2020Day4.sample.txt", "utf8");

var $$require = Belt_SetString.fromArray([
      "byr",
      "hcl",
      "pid",
      "ecl",
      "iyr",
      "hgt",
      "eyr"
    ]);

function parsing(s) {
  return Belt_SetString.fromArray(Belt_Array.keep(Belt_Array.map(s.replace(/[\s]+/g, " ").split(/[\s]+/g), (function (str) {
                        return Belt_Option.mapWithDefault(str, "", (function (x) {
                                        return x;
                                      })).replace(/:[\w#]+/, "");
                      })), (function (x) {
                    return x !== "";
                  })));
}

function judge(s) {
  return Belt_SetString.size(Belt_SetString.intersect(s, $$require)) === 7;
}

console.log(Belt_List.size(Belt_List.keep(Belt_List.map(Belt_List.fromArray(input.split("\n\n")), parsing), judge)));

exports.input = input;
exports.$$require = $$require;
exports.parsing = parsing;
exports.judge = judge;
/* input Not a pure module */
